include: package:lints/recommended.yaml

linter: 
  rules:
    - always_declare_return_types
    - avoid_bool_literals_in_conditional_expressions
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_relative_imports
    - slash_for_doc_comments
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - unnecessary_parenthesis
    - join_return_with_assignment
    - use_string_buffers

formatter:
  page_width: 80
