include: package:lints/recommended.yaml

# Uncomment the following section to specify additional rules.

linter:
  rules:
    - always_declare_return_types
    - directives_ordering
    - prefer_relative_imports
    - sort_pub_dependencies
    - use_string_buffers
    - no_runtimeType_toString
    - avoid_returning_this
    - annotate_redeclares
    - type_annotate_public_apis
    - use_named_constants

formatter:
  page_width: 80
